name: demonstrate_bug_pdfviewer
description: A new Flutter project to demonstrate bug in syncfusion_flutter_pdfviewer
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #syncfusion_flutter_pdfviewer:
   # path: ../flutter_pdf/flutter_pdfviewer
  syncfusion_flutter_pdfviewer: ^19.4.55-beta 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true